### ISSUE TITLE
500 error when turning on some repos

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/github2fedmsg#13]
```
mod_wsgi (pid=18694): Exception occurred processing WSGI script '/usr/share/github2fedmsg/github2fedmsg.wsgi'.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tw2/core/middleware.py", line 204, in __call__
    resp = req.get_response(self.app, catch_exc_info=True)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1292, in send
    application, catch_exc_info=True)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1260, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/site-packages/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/usr/lib/python2.7/site-packages/github2fedmsg/views/webhooks.py", line 220, in repo_toggle_enabled
    toggle_webhook_directly(request, repo, token)
  File "/usr/lib/python2.7/site-packages/github2fedmsg/views/webhooks.py", line 253, in toggle_webhook_directly
    actually_enabled = _get_webhook_status_directly(request, repo, token)
  File "/usr/lib/python2.7/site-packages/github2fedmsg/views/webhooks.py", line 277, in _get_webhook_status_directly
    raise IOError(d)
IOError: {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Not Found', 'status_code': 404}
```

@ryansb reported.  Ryan, can you post here what repos gave you the 500?

**Comment by ryansb** [comment]
I'm attempting to add notifications for [fargo](https://github.com/hudl/fargo). 

gh2fedmsg tries to request https://apps.fedoraproject.org/github2fedmsg/api/github_org_hudl/hudl/fargo/toggle and gets a 500 back.

Response headers:
```
Connection: close
Content-Encoding: gzip
Content-Length: 330
Content-Type: text/html; charset=iso-8859-1
Date: Thu, 05 Feb 2015 17:55:38 GMT
ProxyServer: proxy06.fedoraproject.org
ProxyTime: D=843692
Server: Apache/2.4.6 (Red Hat) mod_wsgi/3.4 Python/2.7.5
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
Vary: Accept-Encoding
```
Response body:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 root@localhost to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

**Comment by ralphbean** [comment]
This likely has to do with private repos.  #14 should surface these errors to the user which is "enough" like we discussed in IRC.

**Comment by ryansb** [comment]
:+1: yup, 14 looks great
